CREATE TABLE [AGENCIAS] (
	NUMERO_BANCO decimal(3) NULL DEFAULT '0',
	NUMERO_AGENCIA decimal(4) NULL DEFAULT '0',
	NOME_AGENCIA varchar(50) NULL,
	ENDERECO_LOGRADOURO varchar(80) NULL,
	ENDERECO_CIDADE varchar(40) NULL,
	ENDERECO_UF varchar(2) NULL,
	ENDERECO_PAIS varchar(40) NULL,
	ENDERECO_CEP varchar(8) NULL,
	TELEFONE_AGENCIA varchar(20) NULL,
	DATA_ABERTURA_AGENCIA datetime NULL,
	DATA_FECHAMENTO_AGENCIA datetime NULL
)
GO
CREATE TABLE [CONTAS] (
	NUMERO_BANCO decimal(3) NULL,
	NUMERO_AGENCIA decimal(4) NULL,
	NUMERO_CONTA varchar(20) NULL,
	TIPO_CONTA decimal(1) NULL,
	DATA_ABERTURA_CONTA datetime NULL,
	DATA_ENCERRAMENTO_CONTA datetime NULL,
	MOVIMENTACAO_CONTA decimal(1) NULL
)
GO
CREATE TABLE [TIPO_CONTA] (
	ID decimal NULL UNIQUE,
	NOME varchar(30) NULL UNIQUE
)
GO
CREATE TABLE [TIPO_MOVIMENTACAO] (
	DESCRICAO text NULL,
	ID decimal NULL
)
GO
CREATE TABLE [TITULARES] (
	NUMERO_BANCO decimal(3) NULL,
	NUMERO_AGENCIA decimal(4) NULL,
	NUMERO_CONTA varchar(20) NULL,
	TIPO_CONTA decimal(1) NULL,
	TIPO_TITULAR varchar(1) NULL,
	PESSOA_INVESTIGADA decimal(1) NULL,
	TIPO_PESSOA_TITULAR decimal(1) NULL,
	CPF_CNPJ_TITULAR decimal(14) NULL,
	NOME_TITULAR varchar(80) NULL,
	NOME_DOC_IDENTIFICACAO varchar(50) NULL,
	NUMER_DOC_IDENTIFICACAO varchar(20) NULL,
	EDNDERECO_LOGRADOURO varchar(80) NULL,
	ENDERECO_CIDADE varchar(40) NULL,
	ENDERECO_UF varchar(2) NULL,
	ENDERECO_PAIS varchar(40) NULL,
	ENDERECO_CEP varchar(8) NULL,
	TELEFONE_PESSOA varchar(20) NULL,
	VALOR_RENDA decimal(14) NULL,
	DATA_ATUALIZACAO_RENDA datetime NULL,
	DATA_INICIO_RELACIONAMENTO datetime NULL,
	DATA_FIM_RELACIONAMENTO datetime NULL
)
GO
CREATE TABLE [TIPO_TITULAR] (
	CODIG varchar(1) NOT NULL,
	DESCRICAO varchar(255) NULL,

  CONSTRAINT [PK_TIPO_TITULAR] PRIMARY KEY CLUSTERED
  (
  [CODIG] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [EXTRATO] (
	CODIGO_CHAVE_EXTRATO decimal(18) NOT NULL,
	NUMERO_BANCO decimal(3) NULL,
	NUMERO_AGENCIA decimal(4) NULL,
	NUMERO_CONTA varchar(20) NULL,
	TIPO_CONTA decimal(1) NULL,
	DATA_LANCAMENTO datetime NULL,
	NUMERO_DOCUMENTO varchar(20) NULL,
	DESCRICAO_LANCAMENTO varchar(50),
	TIPO_LANCAMENTO decimal(3) NULL,
	VALOR_LANCAMENTO decimal NULL,
	NATUREZA_LANCAMENTO varchar(1) NULL,
	VALOR_SALDO decimal NULL,
	NATUREZA_SALDO varchar(1) NULL,
	LOCAL_TRANSACAO varchar(80) NULL,
	
  CONSTRAINT [PK_EXTRATO] PRIMARY KEY CLUSTERED
  (
  [CODIGO_CHAVE_EXTRATO] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [TIPO_LANCAMENTO] (
	CODIGO decimal(3) NOT NULL,
	DESCRICAO varchar(80) NULL,
	
  CONSTRAINT [PK_TIPO_LANCAMENTO] PRIMARY KEY CLUSTERED
  (
  [CODIGO] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [ORIGEM_DESTINO] (
	CODIGO_CHAVE_OD decimal(18) NOT NULL,
	CODIGO_CHAVE_EXTRATO decimal(18) NULL,
	VALOR_TRANSACAO decimal NULL,
	NUMERO_DOCUMENTO_TRANSACAO varchar(20) NULL,
	NUMERO_BANCO_OD decimal(3) NULL,
	NUMERO_AGENCIA_OD decimal(4) NULL,
	NUMERO_CONTA_OD varchar(20) NULL,
	TIPO_CONTA_OD decimal(1) NULL,
	TIPO_PESSOA_OD decimal(1) NULL,
	CPF_CNPJ_OD decimal(14) NULL,
	NOME_PESSOA_OD varchar(80) NULL,
	NOME_DOC_IDENTIFICACAO_OD varchar(50) NULL,
	NUMERO_DOC_IDENTIFICACAO_OD varchar(20) NULL,
	CODIGO_DE_BARRAS varchar(100) NULL,
	NOME_ENDOSSANTE_CHEQUE varchar(80) NULL,
	DOC_ENDOSSANTE_CHEQUE varchar(50) NULL,
	SITUACAO_IDENTIFICACAO decimal(1) NULL,
	OBSERVACAO varchar(250) NULL,
	
  CONSTRAINT [PK_ORIGEM_DESTINO] PRIMARY KEY CLUSTERED
  (
  [CODIGO_CHAVE_OD] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO

GO
INSERT [dbo].[TIPO_CONTA] ([ID], [NOME]) VALUES (CAST(1 AS Decimal(18, 0)), N'CONTA CORRENTE')
GO
INSERT [dbo].[TIPO_CONTA] ([ID], [NOME]) VALUES (CAST(2 AS Decimal(18, 0)), N'CONTA POUPANÇA')
GO
INSERT [dbo].[TIPO_CONTA] ([ID], [NOME]) VALUES (CAST(3 AS Decimal(18, 0)), N'CONTA INVESTIMENTO')
GO
INSERT [dbo].[TIPO_CONTA] ([ID], [NOME]) VALUES (CAST(4 AS Decimal(18, 0)), N'OUTROS')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(101 AS Decimal(3, 0)), N'Cheques')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(102 AS Decimal(3, 0)), N'Encargos')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(103 AS Decimal(3, 0)), N'Estornos')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(104 AS Decimal(3, 0)), N'Lançamento avisado')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(105 AS Decimal(3, 0)), N'Tarifas')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(106 AS Decimal(3, 0)), N'Aplicação')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(107 AS Decimal(3, 0)), N'Empréstimo/Financiamento')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(108 AS Decimal(3, 0)), N'Câmbio')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(109 AS Decimal(3, 0)), N'IOF')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(110 AS Decimal(3, 0)), N'CPMF')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(111 AS Decimal(3, 0)), N'Imposto de Renda')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(112 AS Decimal(3, 0)), N'Pagamento Fornecedores')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(113 AS Decimal(3, 0)), N'Pagamento Salário')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(114 AS Decimal(3, 0)), N'Saque Eletrônico')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(115 AS Decimal(3, 0)), N'Ações')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(117 AS Decimal(3, 0)), N'Transferência entre Contas')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(118 AS Decimal(3, 0)), N'Devolução da Compesação')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(119 AS Decimal(3, 0)), N'Devolução de Cheque Depositado')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(120 AS Decimal(3, 0)), N'Transf. Interbancária (DOC, TED) ')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(121 AS Decimal(3, 0)), N'Antecipação a Fornecedores122 OC/AEROPS')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(201 AS Decimal(3, 0)), N'Depósitos')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(202 AS Decimal(3, 0)), N'Líquido de Cobrança')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(203 AS Decimal(3, 0)), N'Devolução de Cheques ')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(204 AS Decimal(3, 0)), N'Estornos')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(205 AS Decimal(3, 0)), N'Lançamento avisado')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(206 AS Decimal(3, 0)), N'Resgate de Aplicação')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(207 AS Decimal(3, 0)), N'Empréstimo/Financiamento')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(208 AS Decimal(3, 0)), N'Câmbio')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(209 AS Decimal(3, 0)), N'Transferência Interbancária (DOC, TED)')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(210 AS Decimal(3, 0)), N'Ações')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(211 AS Decimal(3, 0)), N'Dividendos')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(212 AS Decimal(3, 0)), N'Seguro')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(213 AS Decimal(3, 0)), N'Transferência entre Contas')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(214 AS Decimal(3, 0)), N'Depósitos Especiais')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(215 AS Decimal(3, 0)), N'Devolução da Compesação')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(216 AS Decimal(3, 0)), N'OCT')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(217 AS Decimal(3, 0)), N'Pagamento Fornecedores')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(218 AS Decimal(3, 0)), N'Pagamento Diversos')
GO
INSERT [dbo].[TIPO_LANCAMENTO] ([CODIGO], [DESCRICAO]) VALUES (CAST(219 AS Decimal(3, 0)), N'Pagamentos Salariais')
GO
