
ALTER TABLE [CONTAS] WITH CHECK ADD CONSTRAINT [CONTAS_fk0] FOREIGN KEY ([NUMERO_BANCO]) REFERENCES [AGENCIAS]([NUMERO_BANCO])
ON UPDATE CASCADE
GO
ALTER TABLE [CONTAS] CHECK CONSTRAINT [CONTAS_fk0]
GO
ALTER TABLE [CONTAS] WITH CHECK ADD CONSTRAINT [CONTAS_fk1] FOREIGN KEY ([NUMERO_AGENCIA]) REFERENCES [AGENCIAS]([NUMERO_AGENCIA])
ON UPDATE CASCADE
GO
ALTER TABLE [CONTAS] CHECK CONSTRAINT [CONTAS_fk1]
GO
ALTER TABLE [CONTAS] WITH CHECK ADD CONSTRAINT [CONTAS_fk2] FOREIGN KEY ([TIPO_CONTA]) REFERENCES [TIPO_CONTA]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [CONTAS] CHECK CONSTRAINT [CONTAS_fk2]
GO
ALTER TABLE [CONTAS] WITH CHECK ADD CONSTRAINT [CONTAS_fk3] FOREIGN KEY ([MOVIMENTACAO_CONTA]) REFERENCES [TIPO_MOVIMENTACAO]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [CONTAS] CHECK CONSTRAINT [CONTAS_fk3]
GO



ALTER TABLE [TITULARES] WITH CHECK ADD CONSTRAINT [TITULARES_fk0] FOREIGN KEY ([NUMERO_BANCO]) REFERENCES [AGENCIAS]([NUMERO_BANCO])
ON UPDATE CASCADE
GO
ALTER TABLE [TITULARES] CHECK CONSTRAINT [TITULARES_fk0]
GO
ALTER TABLE [TITULARES] WITH CHECK ADD CONSTRAINT [TITULARES_fk1] FOREIGN KEY ([NUMERO_AGENCIA]) REFERENCES [AGENCIAS]([NUMERO_AGENCIA])
ON UPDATE CASCADE
GO
ALTER TABLE [TITULARES] CHECK CONSTRAINT [TITULARES_fk1]
GO
ALTER TABLE [TITULARES] WITH CHECK ADD CONSTRAINT [TITULARES_fk2] FOREIGN KEY ([TIPO_CONTA]) REFERENCES [TIPO_CONTA]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [TITULARES] CHECK CONSTRAINT [TITULARES_fk2]
GO
ALTER TABLE [TITULARES] WITH CHECK ADD CONSTRAINT [TITULARES_fk3] FOREIGN KEY ([TIPO_TITULAR]) REFERENCES [TIPO_TITULAR]([CODIG])
ON UPDATE CASCADE
GO
ALTER TABLE [TITULARES] CHECK CONSTRAINT [TITULARES_fk3]
GO


ALTER TABLE [EXTRATO] WITH CHECK ADD CONSTRAINT [EXTRATO_fk0] FOREIGN KEY ([NUMERO_BANCO]) REFERENCES [AGENCIAS]([NUMERO_BANCO])
ON UPDATE CASCADE
GO
ALTER TABLE [EXTRATO] CHECK CONSTRAINT [EXTRATO_fk0]
GO
ALTER TABLE [EXTRATO] WITH CHECK ADD CONSTRAINT [EXTRATO_fk1] FOREIGN KEY ([NUMERO_AGENCIA]) REFERENCES [AGENCIAS]([NUMERO_AGENCIA])
ON UPDATE CASCADE
GO
ALTER TABLE [EXTRATO] CHECK CONSTRAINT [EXTRATO_fk1]
GO
ALTER TABLE [EXTRATO] WITH CHECK ADD CONSTRAINT [EXTRATO_fk2] FOREIGN KEY ([TIPO_CONTA]) REFERENCES [TIPO_CONTA]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [EXTRATO] CHECK CONSTRAINT [EXTRATO_fk2]
GO
ALTER TABLE [EXTRATO] WITH CHECK ADD CONSTRAINT [EXTRATO_fk3] FOREIGN KEY ([TIPO_LANCAMENTO]) REFERENCES [TIPO_LANCAMENTO]([CODIGO])
ON UPDATE CASCADE
GO
ALTER TABLE [EXTRATO] CHECK CONSTRAINT [EXTRATO_fk3]
GO


ALTER TABLE [ORIGEM_DESTINO] WITH CHECK ADD CONSTRAINT [ORIGEM_DESTINO_fk0] FOREIGN KEY ([CODIGO_CHAVE_EXTRATO]) REFERENCES [EXTRATO]([CODIGO_CHAVE_EXTRATO])
ON UPDATE CASCADE
GO
ALTER TABLE [ORIGEM_DESTINO] CHECK CONSTRAINT [ORIGEM_DESTINO_fk0]
GO
ALTER TABLE [ORIGEM_DESTINO] WITH CHECK ADD CONSTRAINT [ORIGEM_DESTINO_fk1] FOREIGN KEY ([NUMERO_BANCO_OD]) REFERENCES [AGENCIAS]([NUMERO_BANCO])
ON UPDATE CASCADE
GO
ALTER TABLE [ORIGEM_DESTINO] CHECK CONSTRAINT [ORIGEM_DESTINO_fk1]
GO
ALTER TABLE [ORIGEM_DESTINO] WITH CHECK ADD CONSTRAINT [ORIGEM_DESTINO_fk2] FOREIGN KEY ([NUMERO_AGENCIA_OD]) REFERENCES [AGENCIAS]([NUMERO_AGENCIA])
ON UPDATE CASCADE
GO
ALTER TABLE [ORIGEM_DESTINO] CHECK CONSTRAINT [ORIGEM_DESTINO_fk2]
GO
ALTER TABLE [ORIGEM_DESTINO] WITH CHECK ADD CONSTRAINT [ORIGEM_DESTINO_fk3] FOREIGN KEY ([NUMERO_CONTA_OD]) REFERENCES [CONTAS]([NUMERO_CONTA])
ON UPDATE CASCADE
GO
ALTER TABLE [ORIGEM_DESTINO] CHECK CONSTRAINT [ORIGEM_DESTINO_fk3]
GO

